"use client";

import { useEffect, useState } from "react";
import { demoCatalog, hydrateCatalog, type SquadCatalog } from "7a0-engine";

export type CatalogSource = "full" | "demo";

/** Load squad catalog from `/catalog.json` (generated by `pnpm build:catalog`). */
export function useGameCatalog(): {
  catalog: SquadCatalog | null;
  source: CatalogSource;
  ready: boolean;
} {
  const [catalog, setCatalog] = useState<SquadCatalog | null>(null);
  const [source, setSource] = useState<CatalogSource>("demo");

  useEffect(() => {
    let cancelled = false;

    fetch("/catalog.json")
      .then((r) => (r.ok ? r.json() : null))
      .then((data: SquadCatalog | null) => {
        if (cancelled) return;
        if (data?.scenarios?.length) {
          setCatalog(hydrateCatalog(data));
          setSource("full");
        } else {
          setCatalog(demoCatalog);
          setSource("demo");
        }
      })
      .catch(() => {
        if (!cancelled) {
          setCatalog(demoCatalog);
          setSource("demo");
        }
      });

    return () => {
      cancelled = true;
    };
  }, []);

  return { catalog, source, ready: catalog !== null };
}
