"use client";

import { useEffect, useState } from "react";
import {
  demoCatalog,
  hydrateCatalog,
  overlayRawExportOnCatalog,
  applyLegendPhotosToCatalog,
  type SquadCatalog,
} from "7a0-engine";
import { CURATED_SQUAD_OVERLAYS } from "../_data/curatedOverlays";

export type CatalogSource = "full" | "demo";

/** Curated positions/overall, then legend-only photos. */
export function prepareGameCatalog(catalog: SquadCatalog): SquadCatalog {
  const { catalog: patched } = overlayRawExportOnCatalog(
    hydrateCatalog(catalog),
    CURATED_SQUAD_OVERLAYS,
  );
  return applyLegendPhotosToCatalog(hydrateCatalog(patched));
}

/** Load squad catalog from `/catalog.json` (generated by `pnpm build:catalog`). */
export function useGameCatalog(): {
  catalog: SquadCatalog | null;
  source: CatalogSource;
  ready: boolean;
} {
  const [catalog, setCatalog] = useState<SquadCatalog | null>(null);
  const [source, setSource] = useState<CatalogSource>("demo");

  useEffect(() => {
    let cancelled = false;

    fetch("/catalog.json")
      .then((r) => (r.ok ? r.json() : null))
      .then((data: SquadCatalog | null) => {
        if (cancelled) return;
        if (data?.scenarios?.length) {
          setCatalog(prepareGameCatalog(data));
          setSource("full");
        } else {
          setCatalog(prepareGameCatalog(demoCatalog));
          setSource("demo");
        }
      })
      .catch(() => {
        if (!cancelled) {
          setCatalog(prepareGameCatalog(demoCatalog));
          setSource("demo");
        }
      });

    return () => {
      cancelled = true;
    };
  }, []);

  return { catalog, source, ready: catalog !== null };
}
