/**
 * Centralised UI strings. Demo ships English only; keeping them in one map lets
 * later locales (PT/ES, MVP RNF-7) drop in without a framework rewrite.
 */
export const STRINGS = {
  title: "NINETY — World Cup Draft",
  subtitle: "Draft · Simulate · Settle it",
  loading: "Loading squad catalog…",
  kickerLeft: "Under the lights",
  kickerRight: "90 minutes",
  heroHome: "Your XI",
  heroAway: "Opponent",
  roll: "Roll the dice",
  simulate: "Kick off",
  vs: "vs",
  noMatch: "Roll the dice to draw your scenario and start the draft.",
  formation: {
    kicker: "Draft setup",
    heading: "Pick your formation",
    hint: "Five shapes on offer — like FIFA Draft. Your choice locks in for this run.",
    confirm: "Start draft",
    drawing: "Drawing…",
    mentality: {
      defensive: "Defensive",
      balanced: "Balanced",
      offensive: "Offensive",
    },
  },
  wizard: {
    label: "Draft setup steps",
    kicker: "World Cup entry",
    name: "Your name",
    formation: "Formation",
    build: "Build XI",
    nameHeading: "What should we call you?",
    nameHint: "Shown on the bracket and in the group tables.",
    nameField: "Your name",
    namePreview: "On screen",
    continue: "Continue",
    stepOf: (current: number, total: number) => `Step ${current} of ${total}`,
  },
  hero: {
    tagline: "Roll the dice. Draft a legend who played there.",
    legendLabel: "Legends who played",
  },
  footer: {
    tagline: "Text-only match simulation — engine decides, timeline narrates.",
    engine: "7a0-engine · seed-deterministic",
  },
  result: {
    kicker: "Full time",
    win: "You take the points",
    loss: "Better luck next match",
    draw: "Honours even",
    seed: "Match seed",
    again: "Play again",
  },
  build: {
    kicker: "Team sheet",
    heading: "Build your XI",
    tactic: "Tactic",
    offensive: "Offensive",
    balanced: "Balanced",
    defensive: "Defensive",
    chemistry: "Chemistry",
    effective: "Effective",
    lambda: "Expected goals (λ)",
    atk: "ATK",
    def: "DEF",
    ovr: "OVR",
    rerollSelection: "Reroll selection",
    rerollYear: "Reroll year",
    selected: "Selected",
    incomplete: "in progress",
    rerollsLeft: (n: number) => `${n} reroll${n === 1 ? "" : "s"} left`,
    playerOvr: "OVR",
    catalogFull: (n: number) => `${n} World Cup squads loaded`,
    catalogDemo: "Demo catalog (3 squads) — run pnpm build:catalog for full data",
    currentRoll: "Current roll",
    turn: (label: string) => `Turn ${label}`,
    squadSize: (n: number) => `${n} players in squad`,
    pickPlayer: "Pick one player for an open slot",
    placeIn: (pos: string) => pos,
    lineup: "Your XI",
    pitch: "Formation",
    empty: "Empty",
    yourXi: "Your XI",
    lineupComplete: "Lineup complete — kick off when ready",
    pickSlot: "Choose where they play",
    hintPlace: "Tap a glowing slot on the pitch — or pick a position below",
    draftInProgress: (turn: number) =>
      turn >= 11 ? "XI complete" : `Draft (${turn}/11)`,
    stepPick: "Step 1 — pick a player",
    stepPlace: "Step 2 — place on the pitch",
    rerollHint: "Costs 1 reroll from your pool",
    squadPool: "Squad pool",
    noOpenSlot: "No open slot for this position",
    slotsFilled: (n: number) => `${n}/11 on the pitch`,
    slotPickerTitle: (pos: string) => `Pick ${pos}`,
    slotPickerEmpty: "No one in this squad fits this slot",
    slotPickerHint: "From the current squad roll",
  },
  matchKicker: "On the air",
  matchTitle: "Live ticker",
  live: "LIVE",
  full: "FULL TIME",
  mode: { fast: "Minute-by-minute", ultra: "Instant" },
  play: "Play",
  pause: "Pause",
  restart: "Restart",
  skip: "Skip to result",
  nextMatch: "Next match",
  period: { first: "First half", second: "Second half" },
  events: {
    kickoff: "Kick-off",
    goal: "GOAL!",
    scores: "scores",
    assist: "assist",
    shot: "Shot",
    saved: "Saved!",
    post: "Off the post!",
    corner: "Corner",
    freekick: "Free kick",
    penalty: "Penalty",
    penScoredLive: "Penalty — buried!",
    penSavedLive: "Penalty — saved!",
    penMissedLive: "Penalty — missed!",
    foul: "Foul",
    yellowCard: "Yellow card",
    redCard: "Red card",
    secondYellow: "Second yellow — off!",
    sentOff: "Sent off!",
    sub: "Substitution",
    offside: "Offside",
    throwin: "Throw-in",
    halftime: "Half-time",
    extraTimeStart: "Extra time",
    extraTimeHt: "Extra time — half-time",
    extraTimeEnd: "End of extra time",
    shootout: "Penalty shootout",
    penScored: "scored",
    penMissed: "missed",
    penWin: "win on penalties",
  },
  campaign: {
    kicker: "Your campaign",
    groupGame: (n: number, total: number) => `Group game ${n} of ${total}`,
    semifinal: "Semifinal",
    final: "Final",
    done: "Campaign complete",
    watchAgain: "Watch any fixture",
  },
  stats: {
    kicker: "Full time",
    heading: "Statistics",
    possession: "Possession",
    shots: "Shots",
    shotsOnTarget: "Shots on target",
    corners: "Corners",
    penalties: "Penalties",
    passes: "Passes",
    fouls: "Fouls",
    cards: "Cards (Y/R)",
    offsides: "Offsides",
    xg: "xG",
  },
  share: {
    kicker: "Share",
    button: "Share highlights",
    building: "Building link…",
    copy: "Copy link",
    copied: "Copied!",
    failed: "Couldn’t build a link",
    hint: "Anyone with the link can replay the goals — no login needed.",
  },
  highlight: {
    kicker: "Goal highlights",
    title: "Match highlights",
    badges: "Badges",
    buildYourOwn: "Draft your own XI →",
    invalidTitle: "Highlight unavailable",
    invalidBody: "This highlight link is broken or has expired.",
  },
  nav: {
    missions: "Missions",
    play: "Play",
    duel: "World Cup",
  },
  missions: {
    kicker: "Objectives",
    heading: "Missions",
    daily: "Daily missions",
    persistent: "Career missions",
    dailyHint: "Fresh objectives every day — completed through any match you play.",
    persistentHint: "Long-haul feats tracked across all your matches.",
    done: "Complete",
    progress: (a: number, b: number) => `${a} / ${b}`,
    category: {
      composition: "Squad",
      result: "Result",
      career: "Career",
    },
    needConvex: "Connect the backend (set NEXT_PUBLIC_CONVEX_URL) to track missions.",
    loading: "Loading missions…",
    completedToast: (n: number) =>
      n === 1 ? "Mission complete!" : `${n} missions complete!`,
  },
  boss: {
    kicker: "Weekly Boss",
    heading: "Beat the Boss",
    sub: (team: string, cup: number) => `${team} ’${String(cup).slice(-2)}`,
    blurb:
      "A real World Cup squad stands in your way all week. You get one shot a day to take them down.",
    challenge: "Challenge the Boss",
    triedToday: "You’ve used today’s attempt — come back tomorrow.",
    beatIt: "Boss beaten! 🏆",
    notYet: "The Boss held on.",
    today: "Today",
    best: "Best this week",
    noResult: "—",
    building: "Drafting…",
    submit: "Face the Boss",
    againTomorrow: "Back tomorrow",
    nameStep: "Name",
    needConvex: "Connect the backend (set NEXT_PUBLIC_CONVEX_URL) to challenge the Boss.",
  },
} as const;
