/**
 * Centralised UI strings. Demo ships English only; keeping them in one map lets
 * later locales (PT/ES, MVP RNF-7) drop in without a framework rewrite.
 */
export const STRINGS = {
  title: "NINETY — World Cup Draft",
  subtitle: "Draft · Simulate · Settle it",
  loading: "Loading squad catalog…",
  kickerLeft: "Under the lights",
  kickerRight: "90 minutes",
  heroHome: "Your XI",
  heroAway: "Opponent",
  roll: "Roll the dice",
  simulate: "Kick off",
  vs: "vs",
  noMatch: "Roll the dice to draw your scenario and start the draft.",
  formation: {
    kicker: "Draft setup",
    heading: "Pick your formation",
    hint: "Five shapes on offer — like FIFA Draft. Your choice locks in for this run.",
    confirm: "Start draft",
    mentality: {
      defensive: "Defensive",
      balanced: "Balanced",
      offensive: "Offensive",
    },
  },
  hero: {
    tagline: "Roll the dice. Draft a legend who played there.",
    legendLabel: "Legends who played",
  },
  footer: {
    tagline: "Text-only match simulation — engine decides, timeline narrates.",
    engine: "7a0-engine · seed-deterministic",
  },
  result: {
    kicker: "Full time",
    win: "You take the points",
    loss: "Better luck next match",
    draw: "Honours even",
    seed: "Match seed",
    again: "Play again",
  },
  build: {
    kicker: "Team sheet",
    heading: "Build your XI",
    tactic: "Tactic",
    offensive: "Offensive",
    balanced: "Balanced",
    defensive: "Defensive",
    chemistry: "Chemistry",
    effective: "Effective",
    lambda: "Expected goals (λ)",
    atk: "ATK",
    def: "DEF",
    ovr: "OVR",
    rerollSelection: "Reroll selection",
    rerollYear: "Reroll year",
    selected: "Selected",
    incomplete: "in progress",
    rerollsLeft: (n: number) => `${n} reroll${n === 1 ? "" : "s"} left`,
    playerOvr: "OVR",
    catalogFull: (n: number) => `${n} World Cup squads loaded`,
    catalogDemo: "Demo catalog (3 squads) — run pnpm build:catalog for full data",
    currentRoll: "Current roll",
    turn: (label: string) => `Turn ${label}`,
    squadSize: (n: number) => `${n} players in squad`,
    pickPlayer: "Pick one player for an open slot",
    placeIn: (pos: string) => pos,
    lineup: "Your XI",
    pitch: "Formation",
    empty: "Empty",
    yourXi: "Your XI",
    lineupComplete: "Lineup complete — kick off when ready",
    pickSlot: "Choose where they play",
    hintPlace: "Tap a glowing slot on the pitch — or pick a position below",
    draftInProgress: (turn: number) =>
      turn >= 11 ? "XI complete" : `Draft (${turn}/11)`,
    stepPick: "Step 1 — pick a player",
    stepPlace: "Step 2 — place on the pitch",
    rerollHint: "Costs 1 reroll from your pool",
    squadPool: "Squad pool",
    noOpenSlot: "No open slot for this position",
    slotsFilled: (n: number) => `${n}/11 on the pitch`,
  },
  matchKicker: "On the air",
  matchTitle: "Live ticker",
  live: "LIVE",
  full: "FULL TIME",
  mode: { fast: "Minute-by-minute", ultra: "Instant" },
  play: "Play",
  pause: "Pause",
  restart: "Restart",
  skip: "Skip to result",
  stats: {
    kicker: "Full time",
    heading: "Statistics",
    possession: "Possession",
    shots: "Shots",
    shotsOnTarget: "Shots on target",
    corners: "Corners",
    penalties: "Penalties",
    passes: "Passes",
    xg: "xG",
  },
} as const;
