/**
 * Centralised UI strings. Demo ships English only; keeping them in one map lets
 * later locales (PT/ES, MVP RNF-7) drop in without a framework rewrite.
 */
export const STRINGS = {
  title: "7a0 — Match Viewer",
  subtitle: "Roll a scenario, build your XI from real squad players, simulate, and read the match as text.",
  roll: "Roll scenario",
  simulate: "Simulate",
  vs: "vs",
  noMatch: "Roll a fixture and simulate to begin.",
  build: {
    heading: "Build",
    tactic: "Tactic",
    offensive: "Offensive",
    balanced: "Balanced",
    defensive: "Defensive",
    chemistry: "Chemistry",
    effective: "Effective",
    lambda: "Expected goals (λ)",
    atk: "ATK",
    def: "DEF",
    ovr: "OVR",
    reroll: "Reroll",
    emergencyReroll: "Emergency reroll",
    selected: "Selected",
    incomplete: "in progress",
    rerollsLeft: (n: number) => `${n} reroll${n === 1 ? "" : "s"} left`,
    force: "Force",
  },
  mode: { fast: "Ticker (minute-by-minute)", ultra: "Instant result" },
  play: "Play",
  pause: "Pause",
  restart: "Restart",
  skip: "Skip to result",
  stats: {
    heading: "Statistics",
    possession: "Possession",
    shots: "Shots",
    shotsOnTarget: "Shots on target",
    corners: "Corners",
    penalties: "Penalties",
    passes: "Passes",
    xg: "xG",
  },
} as const;
