/**
 * The single catalog the duel is played on, shared byte-for-byte by the server
 * (this module) and the duel client (`app/duel`). Determinism of the shared
 * draft seed depends on both sides rolling scenarios from the *identical*
 * scenario list.
 *
 * Source of truth: `apps/web/public/catalog.json` — the full 85-nation catalog
 * generated by `pnpm build:catalog` (root). The server bundles that exact file;
 * the duel client `fetch`es the same file at `/catalog.json`. Because both sides
 * read the identical bytes, a replayed draft action log rolls the same scenarios
 * and the server can validate it. If the client cannot load the file it must
 * NOT fall back to a different catalog — see `app/duel/page.tsx`.
 *
 * Both sides hydrate the JSON the same way (`hydrateCatalog`) so inferred
 * `positionSource` / `overall` backfills match the duel client.
 */
import { hydrateCatalog, type SquadCatalog } from "7a0-engine/dist";
import fullCatalog from "../public/catalog.json";

// Cast through `unknown`: the JSON's inferred literal type is structurally
// looser than `SquadCatalog` (e.g. `positionSource: string`), but the file is
// produced by the engine's own `build:catalog` so the shape is authoritative.
export const duelCatalog: SquadCatalog = hydrateCatalog(
  fullCatalog as unknown as SquadCatalog,
);
