/**
 * Demo squad catalog — full squads with autoral `force` values (0–255).
 *
 * TODO(data): replace via `pnpm import:squads` when licensed squad JSON exists.
 */

import { normalizeCatalog, type RawCatalogExport, type SquadCatalog } from "./catalog.js";

const raw: RawCatalogExport = {
  scenarios: [
    {
      id: "brazil-1970",
      team: "Brazil",
      cup: 1970,
      players: [
        { id: "br70-felix", name: "Félix", naturalPosition: "GK", shirtNumber: 1, force: 210 },
        { id: "br70-carlos-alberto", name: "Carlos Alberto", naturalPosition: "RB", shirtNumber: 4, force: 238 },
        { id: "br70-brito", name: "Brito", naturalPosition: "RCB", shirtNumber: 2, force: 220 },
        { id: "br70-piazza", name: "Piazza", naturalPosition: "LCB", shirtNumber: 3, force: 225 },
        { id: "br70-everaldo", name: "Everaldo", naturalPosition: "LB", shirtNumber: 6, force: 222 },
        { id: "br70-clodoaldo", name: "Clodoaldo", naturalPosition: "RCM", shirtNumber: 5, force: 228 },
        { id: "br70-gerson", name: "Gerson", naturalPosition: "CM", shirtNumber: 8, force: 232 },
        { id: "br70-rivellino", name: "Rivelino", naturalPosition: "LCM", shirtNumber: 10, force: 235 },
        { id: "br70-jairzinho", name: "Jairzinho", naturalPosition: "RW", shirtNumber: 7, force: 240 },
        { id: "br70-pelé", name: "Pelé", naturalPosition: "ST", shirtNumber: 9, force: 245 },
        { id: "br70-tostao", name: "Tostão", naturalPosition: "LW", shirtNumber: 11, force: 236 },
        { id: "br70-leao", name: "Leão", naturalPosition: "GK", shirtNumber: 12, force: 198 },
        { id: "br70-bellini", name: "Bellini", naturalPosition: "CB", shirtNumber: 13, force: 205 },
        { id: "br70-edú", name: "Edu", naturalPosition: "CM", shirtNumber: 14, force: 212 },
        { id: "br70-waltencir", name: "Waltencir", naturalPosition: "ST", shirtNumber: 15, force: 200 },
        { id: "br70-joao", name: "João", naturalPosition: "GK", shirtNumber: 22, force: 185 },
        { id: "br70-baldocchi", name: "Baldocchi", naturalPosition: "CB", shirtNumber: 16, force: 190 },
        { id: "br70-felix-alt", name: "Marco Antônio", naturalPosition: "RB", shirtNumber: 17, force: 195 },
        { id: "br70-roberto", name: "Roberto", naturalPosition: "LB", shirtNumber: 18, force: 192 },
        { id: "br70-dario", name: "Dario", naturalPosition: "ST", shirtNumber: 19, force: 188 },
        { id: "br70-resendes", name: "Resende", naturalPosition: "CM", shirtNumber: 20, force: 182 },
        { id: "br70-zagallo", name: "Zagallo", naturalPosition: "LW", shirtNumber: 21, force: 215 },
      ],
    },
    {
      id: "italy-1982",
      team: "Italy",
      cup: 1982,
      players: [
        { id: "it82-zoff", name: "Zoff", naturalPosition: "GK", shirtNumber: 1, force: 228 },
        { id: "it82-gentile", name: "Gentile", naturalPosition: "RB", shirtNumber: 8, force: 218 },
        { id: "it82-scirea", name: "Scirea", naturalPosition: "RCB", shirtNumber: 5, force: 232 },
        { id: "it82-cabrini", name: "Cabrini", naturalPosition: "LB", shirtNumber: 3, force: 220 },
        { id: "it82-collovati", name: "Collovati", naturalPosition: "LCB", shirtNumber: 6, force: 215 },
        { id: "it82-antognoni", name: "Antognoni", naturalPosition: "CM", shirtNumber: 10, force: 222 },
        { id: "it82-tardelli", name: "Tardelli", naturalPosition: "RCM", shirtNumber: 11, force: 225 },
        { id: "it82-rossi", name: "Rossi", naturalPosition: "ST", shirtNumber: 9, force: 238 },
        { id: "it82-conti", name: "Conti", naturalPosition: "RW", shirtNumber: 7, force: 218 },
        { id: "it82-graziani", name: "Graziani", naturalPosition: "LW", shirtNumber: 12, force: 215 },
        { id: "it82-oriani", name: "Oriani", naturalPosition: "LCM", shirtNumber: 14, force: 210 },
        { id: "it82-buffon", name: "Buffon", naturalPosition: "GK", shirtNumber: 22, force: 175 },
        { id: "it82-baresi", name: "Baresi", naturalPosition: "CB", shirtNumber: 4, force: 205 },
        { id: "it82-altobelli", name: "Altobelli", naturalPosition: "ST", shirtNumber: 18, force: 228 },
        { id: "it82-vierchowod", name: "Vierchowod", naturalPosition: "CB", shirtNumber: 15, force: 212 },
        { id: "it82-bergomi", name: "Bergomi", naturalPosition: "CB", shirtNumber: 2, force: 208 },
        { id: "it82-oriali", name: "Oriali", naturalPosition: "DM", shirtNumber: 13, force: 200 },
        { id: "it82-marini", name: "Marini", naturalPosition: "CM", shirtNumber: 16, force: 195 },
        { id: "it82-salceti", name: "Salceti", naturalPosition: "CB", shirtNumber: 17, force: 188 },
        { id: "it82-vignola", name: "Vignola", naturalPosition: "LB", shirtNumber: 19, force: 185 },
        { id: "it82-serena", name: "Serena", naturalPosition: "ST", shirtNumber: 20, force: 192 },
        { id: "it82-dino", name: "Dino", naturalPosition: "CM", shirtNumber: 21, force: 180 },
      ],
    },
    {
      id: "argentina-1986",
      team: "Argentina",
      cup: 1986,
      players: [
        { id: "ar86-pumpido", name: "Pumpido", naturalPosition: "GK", shirtNumber: 18, force: 218 },
        { id: "ar86-batista", name: "Batista", naturalPosition: "RCB", shirtNumber: 2, force: 210 },
        { id: "ar86-brown", name: "Brown", naturalPosition: "LCB", shirtNumber: 5, force: 215 },
        { id: "ar86-ruggeri", name: "Ruggeri", naturalPosition: "CB", shirtNumber: 19, force: 212 },
        { id: "ar86-burruchaga", name: "Burruchaga", naturalPosition: "RCM", shirtNumber: 7, force: 228 },
        { id: "ar86-enrique", name: "Enrique", naturalPosition: "CM", shirtNumber: 12, force: 218 },
        { id: "ar86-maradona", name: "Maradona", naturalPosition: "AM", positions: ["AM", "CAM", "CF", "LW", "CM"], positionSource: "api", shirtNumber: 10, force: 248 },
        { id: "ar86-valdano", name: "Valdano", naturalPosition: "ST", positions: ["ST"], positionSource: "api", shirtNumber: 11, force: 232 },
        { id: "ar86-giusti", name: "Giusti", naturalPosition: "DM", shirtNumber: 14, force: 208 },
        { id: "ar86-olarticoechea", name: "Olarticoechea", naturalPosition: "LB", shirtNumber: 16, force: 205 },
        { id: "ar86-cuciuffo", name: "Cuciuffo", naturalPosition: "RB", shirtNumber: 9, force: 212 },
        { id: "ar86-tapia", name: "Tapia", naturalPosition: "CM", shirtNumber: 21, force: 200 },
        { id: "ar86-sergio", name: "Sergio Batista", naturalPosition: "DM", shirtNumber: 6, force: 202 },
        { id: "ar86-calderon", name: "Calderón", naturalPosition: "ST", positions: ["ST"], positionSource: "api", shirtNumber: 17, force: 195 },
        { id: "ar86-borghi", name: "Borghi", naturalPosition: "AM", shirtNumber: 20, force: 198 },
        { id: "ar86-nery", name: "Nery Pumpido", naturalPosition: "GK", shirtNumber: 1, force: 190 },
        { id: "ar86-islas", name: "Islas", naturalPosition: "GK", shirtNumber: 22, force: 185 },
        { id: "ar86-passarella", name: "Passarella", naturalPosition: "CB", shirtNumber: 3, force: 220 },
        { id: "ar86-clausen", name: "Clausen", naturalPosition: "ST", shirtNumber: 13, force: 188 },
        { id: "ar86-albaladejo", name: "Albaladejo", naturalPosition: "LB", shirtNumber: 15, force: 182 },
        { id: "ar86-garza", name: "Garza", naturalPosition: "CM", shirtNumber: 4, force: 178 },
        { id: "ar86-lorente", name: "Lorente", naturalPosition: "CB", shirtNumber: 8, force: 192 },
      ],
    },
    {
      id: "portugal-2006",
      team: "Portugal",
      cup: 2006,
      players: [
        { id: "pt06-ricardo", name: "Ricardo", naturalPosition: "GK", shirtNumber: 1, force: 210 },
        { id: "pt06-paulo-ferreira", name: "Paulo Ferreira", naturalPosition: "RB", shirtNumber: 2, force: 215 },
        { id: "pt06-carvalho", name: "Ricardo Carvalho", naturalPosition: "RCB", shirtNumber: 5, force: 225 },
        { id: "pt06-andrade", name: "Jorge Andrade", naturalPosition: "LCB", shirtNumber: 4, force: 210 },
        { id: "pt06-valente", name: "Nuno Valente", naturalPosition: "LB", shirtNumber: 14, force: 205 },
        { id: "pt06-costinha", name: "Costinha", naturalPosition: "RCM", shirtNumber: 6, force: 215 },
        { id: "pt06-maniche", name: "Maniche", naturalPosition: "CM", shirtNumber: 18, force: 220 },
        { id: "pt06-deco", name: "Deco", naturalPosition: "LCM", shirtNumber: 10, force: 235 },
        { id: "pt06-ronaldo", name: "Cristiano Ronaldo", naturalPosition: "RW", shirtNumber: 17, force: 240 },
        { id: "pt06-pauleta", name: "Pauleta", naturalPosition: "ST", shirtNumber: 9, force: 225 },
        { id: "pt06-figo", name: "Luís Figo", naturalPosition: "LW", shirtNumber: 7, force: 230 },
        { id: "pt06-quim", name: "Quim", naturalPosition: "GK", shirtNumber: 22, force: 180 },
        { id: "pt06-meira", name: "Fernando Meira", naturalPosition: "CB", shirtNumber: 21, force: 200 },
        { id: "pt06-petit", name: "Petit", naturalPosition: "DM", shirtNumber: 15, force: 210 },
        { id: "pt06-tiago", name: "Tiago", naturalPosition: "CM", shirtNumber: 16, force: 205 },
        { id: "pt06-simao", name: "Simão Sabrosa", naturalPosition: "AM", shirtNumber: 11, force: 215 },
        { id: "pt06-postiga", name: "Hélder Postiga", naturalPosition: "ST", shirtNumber: 20, force: 200 },
        { id: "pt06-miguel", name: "Miguel", naturalPosition: "RB", shirtNumber: 13, force: 195 },
        { id: "pt06-ferreira-alt", name: "Armando Petit", naturalPosition: "LB", shirtNumber: 19, force: 188 },
        { id: "pt06-boa-morte", name: "Boa Morte", naturalPosition: "LW", shirtNumber: 12, force: 198 },
        { id: "pt06-rui-costa", name: "Rui Costa", naturalPosition: "AM", shirtNumber: 8, force: 222 },
      ],
    },
    {
      id: "spain-2010",
      team: "Spain",
      cup: 2010,
      players: [
        { id: "es10-casillas", name: "Iker Casillas", naturalPosition: "GK", shirtNumber: 1, force: 235 },
        { id: "es10-ramos", name: "Sergio Ramos", naturalPosition: "RB", shirtNumber: 15, force: 220 },
        { id: "es10-pique", name: "Gerard Piqué", naturalPosition: "RCB", shirtNumber: 3, force: 225 },
        { id: "es10-puyol", name: "Carles Puyol", naturalPosition: "LCB", shirtNumber: 5, force: 228 },
        { id: "es10-capdevila", name: "Joan Capdevila", naturalPosition: "LB", shirtNumber: 11, force: 205 },
        { id: "es10-busquets", name: "Sergio Busquets", naturalPosition: "RCM", shirtNumber: 16, force: 210 },
        { id: "es10-alonso", name: "Xabi Alonso", naturalPosition: "CM", shirtNumber: 14, force: 222 },
        { id: "es10-xavi", name: "Xavi Hernández", naturalPosition: "LCM", shirtNumber: 8, force: 240 },
        { id: "es10-pedro", name: "Pedro Rodríguez", naturalPosition: "RW", shirtNumber: 18, force: 215 },
        { id: "es10-villa", name: "David Villa", naturalPosition: "ST", shirtNumber: 7, force: 232 },
        { id: "es10-iniesta", name: "Andrés Iniesta", naturalPosition: "LW", shirtNumber: 6, force: 245 },
        { id: "es10-reina", name: "Pepe Reina", naturalPosition: "GK", shirtNumber: 13, force: 200 },
        { id: "es10-marchena", name: "Carlos Marchena", naturalPosition: "CB", shirtNumber: 4, force: 195 },
        { id: "es10-arbeloa", name: "Álvaro Arbeloa", naturalPosition: "RB", shirtNumber: 17, force: 195 },
        { id: "es10-fabregas", name: "Cesc Fàbregas", naturalPosition: "CM", shirtNumber: 4, force: 220 },
        { id: "es10-silva", name: "David Silva", naturalPosition: "AM", shirtNumber: 21, force: 225 },
        { id: "es10-torres", name: "Fernando Torres", naturalPosition: "ST", shirtNumber: 9, force: 228 },
        { id: "es10-valdes", name: "Víctor Valdés", naturalPosition: "GK", shirtNumber: 22, force: 190 },
        { id: "es10-albiol", name: "Raúl Albiol", naturalPosition: "CB", shirtNumber: 19, force: 195 },
        { id: "es10-navas", name: "Jesús Navas", naturalPosition: "RW", shirtNumber: 12, force: 200 },
        { id: "es10-llorente", name: "Fernando Llorente", naturalPosition: "ST", shirtNumber: 20, force: 205 },
      ],
    },
    {
      id: "germany-2014",
      team: "Germany",
      cup: 2014,
      players: [
        { id: "de14-neuer", name: "Manuel Neuer", naturalPosition: "GK", shirtNumber: 1, force: 238 },
        { id: "de14-lahm", name: "Philipp Lahm", naturalPosition: "RB", shirtNumber: 16, force: 225 },
        { id: "de14-boateng", name: "Jérôme Boateng", naturalPosition: "RCB", shirtNumber: 17, force: 222 },
        { id: "de14-hummels", name: "Mats Hummels", naturalPosition: "LCB", shirtNumber: 5, force: 222 },
        { id: "de14-howedes", name: "Benedikt Höwedes", naturalPosition: "LB", shirtNumber: 4, force: 210 },
        { id: "de14-khedira", name: "Sami Khedira", naturalPosition: "RCM", shirtNumber: 6, force: 215 },
        { id: "de14-schweinsteiger", name: "Bastian Schweinsteiger", naturalPosition: "CM", shirtNumber: 7, force: 230 },
        { id: "de14-kroos", name: "Toni Kroos", naturalPosition: "LCM", shirtNumber: 18, force: 232 },
        { id: "de14-muller", name: "Thomas Müller", naturalPosition: "RW", shirtNumber: 13, force: 235 },
        { id: "de14-klose", name: "Miroslav Klose", naturalPosition: "ST", shirtNumber: 11, force: 220 },
        { id: "de14-ozil", name: "Mesut Özil", naturalPosition: "LW", shirtNumber: 8, force: 228 },
        { id: "de14-weidenfeller", name: "Roman Weidenfeller", naturalPosition: "GK", shirtNumber: 12, force: 195 },
        { id: "de14-mertesacker", name: "Per Mertesacker", naturalPosition: "CB", shirtNumber: 17, force: 205 },
        { id: "de14-durm", name: "Erik Durm", naturalPosition: "LB", shirtNumber: 23, force: 190 },
        { id: "de14-draxler", name: "Julian Draxler", naturalPosition: "AM", shirtNumber: 19, force: 200 },
        { id: "de14-gotze", name: "Mario Götze", naturalPosition: "ST", shirtNumber: 19, force: 225 },
        { id: "de14-schurrle", name: "André Schürrle", naturalPosition: "LW", shirtNumber: 9, force: 210 },
        { id: "de14-zieler", name: "Ron-Robert Zieler", naturalPosition: "GK", shirtNumber: 22, force: 180 },
        { id: "de14-mustafi", name: "Shkodran Mustafi", naturalPosition: "CB", shirtNumber: 21, force: 195 },
        { id: "de14-kramer", name: "Christoph Kramer", naturalPosition: "DM", shirtNumber: 23, force: 190 },
        { id: "de14-podolski", name: "Lukas Podolski", naturalPosition: "ST", shirtNumber: 10, force: 215 },
      ],
    },
    {
      id: "france-1998",
      team: "France",
      cup: 1998,
      players: [
        { id: "fr98-barthez", name: "Fabien Barthez", naturalPosition: "GK", shirtNumber: 1, force: 225 },
        { id: "fr98-thuram", name: "Lilian Thuram", naturalPosition: "RB", shirtNumber: 15, force: 222 },
        { id: "fr98-desailly", name: "Marcel Desailly", naturalPosition: "RCB", shirtNumber: 8, force: 225 },
        { id: "fr98-blanc", name: "Laurent Blanc", naturalPosition: "LCB", shirtNumber: 5, force: 222 },
        { id: "fr98-lizarazu", name: "Bixente Lizarazu", naturalPosition: "LB", shirtNumber: 3, force: 215 },
        { id: "fr98-deschamps", name: "Didier Deschamps", naturalPosition: "RCM", shirtNumber: 7, force: 215 },
        { id: "fr98-petit", name: "Emmanuel Petit", naturalPosition: "CM", shirtNumber: 11, force: 220 },
        { id: "fr98-zidane", name: "Zinedine Zidane", naturalPosition: "LCM", shirtNumber: 10, force: 248 },
        { id: "fr98-djorkaeff", name: "Youri Djorkaeff", naturalPosition: "RW", shirtNumber: 6, force: 225 },
        { id: "fr98-guivarch", name: "Stéphane Guivarc'h", naturalPosition: "ST", shirtNumber: 9, force: 205 },
        { id: "fr98-henry", name: "Thierry Henry", naturalPosition: "LW", shirtNumber: 12, force: 230 },
        { id: "fr98-lama", name: "Bernard Lama", naturalPosition: "GK", shirtNumber: 16, force: 190 },
        { id: "fr98-leboeuf", name: "Frank Leboeuf", naturalPosition: "CB", shirtNumber: 2, force: 205 },
        { id: "fr98-karembeu", name: "Christian Karembeu", naturalPosition: "RB", shirtNumber: 19, force: 200 },
        { id: "fr98-dugarry", name: "Christophe Dugarry", naturalPosition: "ST", shirtNumber: 14, force: 210 },
        { id: "fr98-pires", name: "Robert Pirès", naturalPosition: "AM", shirtNumber: 22, force: 215 },
        { id: "fr98-trezeguet", name: "David Trezeguet", naturalPosition: "ST", shirtNumber: 20, force: 218 },
        { id: "fr98-charbonnier", name: "Lionel Charbonnier", naturalPosition: "GK", shirtNumber: 23, force: 175 },
        { id: "fr98-diomede", name: "Bernard Diomède", naturalPosition: "LW", shirtNumber: 17, force: 195 },
        { id: "fr98-boghossian", name: "Alain Boghossian", naturalPosition: "CM", shirtNumber: 4, force: 190 },
        { id: "fr98-candela", name: "Vincent Candela", naturalPosition: "LB", shirtNumber: 18, force: 195 },
      ],
    },
    {
      id: "england-1966",
      team: "England",
      cup: 1966,
      players: [
        { id: "en66-banks", name: "Gordon Banks", naturalPosition: "GK", shirtNumber: 1, force: 230 },
        { id: "en66-cohen", name: "George Cohen", naturalPosition: "RB", shirtNumber: 2, force: 210 },
        { id: "en66-jcharlton", name: "Jack Charlton", naturalPosition: "RCB", shirtNumber: 5, force: 215 },
        { id: "en66-moore", name: "Bobby Moore", naturalPosition: "LCB", shirtNumber: 6, force: 235 },
        { id: "en66-wilson", name: "Ray Wilson", naturalPosition: "LB", shirtNumber: 3, force: 210 },
        { id: "en66-ball", name: "Alan Ball", naturalPosition: "RCM", shirtNumber: 7, force: 220 },
        { id: "en66-stiles", name: "Nobby Stiles", naturalPosition: "CM", shirtNumber: 4, force: 210 },
        { id: "en66-bcharlton", name: "Bobby Charlton", naturalPosition: "LCM", shirtNumber: 9, force: 240 },
        { id: "en66-hurst", name: "Geoff Hurst", naturalPosition: "RW", shirtNumber: 10, force: 230 },
        { id: "en66-hunt", name: "Roger Hunt", naturalPosition: "ST", shirtNumber: 8, force: 222 },
        { id: "en66-peters", name: "Martin Peters", naturalPosition: "LW", shirtNumber: 16, force: 225 },
        { id: "en66-bonetti", name: "Peter Bonetti", naturalPosition: "GK", shirtNumber: 21, force: 190 },
        { id: "en66-armfield", name: "Jimmy Armfield", naturalPosition: "RB", shirtNumber: 19, force: 195 },
        { id: "en66-nhunter", name: "Norman Hunter", naturalPosition: "CB", shirtNumber: 15, force: 200 },
        { id: "en66-paine", name: "Terry Paine", naturalPosition: "AM", shirtNumber: 17, force: 195 },
        { id: "en66-greaves", name: "Jimmy Greaves", naturalPosition: "ST", shirtNumber: 20, force: 220 },
        { id: "en66-springett", name: "Ron Springett", naturalPosition: "GK", shirtNumber: 22, force: 180 },
        { id: "en66-byrne", name: "Gerry Byrne", naturalPosition: "LB", shirtNumber: 13, force: 190 },
        { id: "en66-eastham", name: "George Eastham", naturalPosition: "CM", shirtNumber: 18, force: 188 },
        { id: "en66-callaghan", name: "Ian Callaghan", naturalPosition: "RW", shirtNumber: 14, force: 195 },
        { id: "en66-connelly", name: "John Connelly", naturalPosition: "LW", shirtNumber: 11, force: 192 },
      ],
    },
  ],
};

/** Demo catalog — not the full live-game dataset. */
export const demoCatalog: SquadCatalog = normalizeCatalog(raw);
